package report

import (
	"fmt"
	"strings"
	"time"

	"github.com/Arsenalist/prx/internal/metrics"
)

// FormatMarkdown returns the analysis result as a markdown document.
func FormatMarkdown(result *metrics.AnalysisResult) string {
	var sb strings.Builder

	// Title
	title := "PR Metrics Report"
	if len(result.Meta.Repos) == 1 {
		title = fmt.Sprintf("PR Metrics: %s", result.Meta.Repos[0])
	} else if result.Meta.Team != "" {
		title = fmt.Sprintf("PR Metrics: %s", result.Meta.Team)
	}
	sb.WriteString(fmt.Sprintf("# %s\n\n", title))
	sb.WriteString(fmt.Sprintf("**Date Range:** %s to %s\n\n", result.Meta.DateRange.Start, result.Meta.DateRange.End))
	sb.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().Format("2006-01-02 15:04")))

	// Summary
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")
	sb.WriteString(fmt.Sprintf("| Total PRs | %d |\n", result.Summary.TotalPRs))
	sb.WriteString(fmt.Sprintf("| Merged | %d |\n", result.Summary.MergedPRs))
	sb.WriteString(fmt.Sprintf("| Closed (not merged) | %d |\n", result.Summary.ClosedPRs))
	sb.WriteString(fmt.Sprintf("| Open | %d |\n", result.Summary.OpenPRs))
	sb.WriteString(fmt.Sprintf("| Unique Authors | %d |\n", result.Summary.UniqueAuthors))
	sb.WriteString(fmt.Sprintf("| Total LOC | %d |\n", result.Summary.LOC.Total))
	sb.WriteString(fmt.Sprintf("| Test LOC | %d |\n", result.Summary.LOC.Test))
	sb.WriteString(fmt.Sprintf("| Production LOC | %d |\n", result.Summary.LOC.Production))
	sb.WriteString(fmt.Sprintf("| Avg LOC/PR | %.0f |\n", result.Summary.LOC.AvgPerPR))
	sb.WriteString(fmt.Sprintf("| Avg Time to Merge | %s |\n", FormatDuration(result.Summary.Timing.AvgTimeToMergeHours)))
	sb.WriteString(fmt.Sprintf("| Median Time to Merge | %s |\n", FormatDuration(result.Summary.Timing.MedianTimeToMergeHours)))
	sb.WriteString("\n")

	// Developer Metrics
	if len(result.Developers) > 0 {
		sb.WriteString("## Developer Metrics\n\n")
		sb.WriteString("| Developer | Merged | PRs/Wk | Avg LOC | Avg Test | Avg Prod | Avg→Open | Avg→Merge | Avg Total |\n")
		sb.WriteString("|-----------|--------|--------|---------|----------|----------|----------|-----------|----------|\n")
		for _, dev := range result.Developers {
			sb.WriteString(fmt.Sprintf("| %s | %d | %.2f | %.0f | %.0f | %.0f | %s | %s | %s |\n",
				dev.Login, dev.MergedPRs, dev.PRsPerWeek,
				dev.LOC.AvgTotal, dev.LOC.AvgTest, dev.LOC.AvgProduction,
				FormatDuration(dev.Timing.AvgTimeToOpenHours),
				FormatDuration(dev.Timing.AvgTimeToMergeHours),
				FormatDuration(dev.Timing.AvgTotalTimeHours),
			))
		}
		sb.WriteString("\n")
	}

	// Slowest PRs
	if len(result.SlowestPRs) > 0 {
		sb.WriteString("## Slowest PRs\n\n")
		sb.WriteString("| PR# | Author | Title | →Open | Draft | →Merge | Total | LOC |\n")
		sb.WriteString("|-----|--------|-------|-------|-------|--------|-------|-----|\n")
		for _, pr := range result.SlowestPRs {
			title := pr.Title
			if len(title) > 50 {
				title = title[:47] + "..."
			}
			sb.WriteString(fmt.Sprintf("| [#%d](%s) | %s | %s | %s | %s | %s | %s | %d |\n",
				pr.Number, pr.URL, pr.Author, title,
				FormatDuration(pr.TimeToOpenHours),
				FormatDuration(pr.DraftTimeHours),
				FormatDuration(pr.TimeToMergeHours),
				FormatDuration(pr.TotalTimeHours),
				pr.LOCTotal,
			))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n*Generated by [prx](https://github.com/Arsenalist/prx)*\n")

	return sb.String()
}

// MarkdownFilename generates the output filename for a markdown report.
func MarkdownFilename(repos []string, team string, date string) string {
	if team != "" {
		return fmt.Sprintf("%s-%s.md", team, date)
	}
	if len(repos) == 1 {
		name := strings.ReplaceAll(repos[0], "/", "-")
		return fmt.Sprintf("%s-%s.md", name, date)
	}
	return fmt.Sprintf("multi-repo-%d-repos-%s.md", len(repos), date)
}
